[package]
name = "rusciify"
version = "0.1.0"

[dependencies]
quicli = "0.4"
structopt = "0.2"
termcolor = "1.1.0"
image = "0.23.14"
rusttype = "0.9.2"

[lib]
name = "rusciify"
path = "src/lib.rs"

[[bin]]
name = "rusciify"
path = "src/bin/main.rs"